/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patientrecordsystem;

import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author benja
 */
public class Diagnosis extends javax.swing.JFrame {

    Connection conn2 = null;
    PreparedStatement p3 = null;
    ResultSet r3 = null;

    public Diagnosis() {
        initComponents();
        TableDiag();
        Date();
        Time();
    }

    void Date() {
        Date d1 = new Date();
        SimpleDateFormat s1 = new SimpleDateFormat("yyyy-MM-dd");
        jTextField1didate.setText(s1.format(d1));

    }

    void Time() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d1 = new Date();
                SimpleDateFormat s1 = new SimpleDateFormat("hh:mm:ss");
                jTextField2ditime.setText(s1.format(d1));

            }

        }).start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1dpid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1diagnosis = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton1savediagnosis = new javax.swing.JButton();
        jButton2openasses = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2medication = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1dreport = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jTextField1didate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField2ditime = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField1searchdiagpid = new javax.swing.JTextField();
        jButton1previewemail = new javax.swing.JButton();
        jButton1ddreset = new javax.swing.JButton();
        jButton1dlogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DIAGNOSIS AND MEDICATION DASHBOARD");

        jLabel2.setText("Patient Id:");

        jTextField1dpid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1dpidKeyPressed(evt);
            }
        });

        jLabel3.setText("Diagnosis Report:");

        jTable1diagnosis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jTable1diagnosis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1diagnosisMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1diagnosis);

        jLabel4.setText("Prescribed Medication:");

        jButton1savediagnosis.setText("Save Diagnosis");
        jButton1savediagnosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1savediagnosisActionPerformed(evt);
            }
        });

        jButton2openasses.setText("Open Assessent");
        jButton2openasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2openassesActionPerformed(evt);
            }
        });

        jTextArea2medication.setColumns(20);
        jTextArea2medication.setLineWrap(true);
        jTextArea2medication.setRows(5);
        jTextArea2medication.setWrapStyleWord(true);
        jTextArea2medication.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane4.setViewportView(jTextArea2medication);

        jTextArea1dreport.setColumns(20);
        jTextArea1dreport.setLineWrap(true);
        jTextArea1dreport.setRows(5);
        jTextArea1dreport.setToolTipText("");
        jTextArea1dreport.setWrapStyleWord(true);
        jScrollPane5.setViewportView(jTextArea1dreport);

        jLabel5.setText("Date:");

        jTextField1didate.setEditable(false);

        jLabel6.setText("Time:");

        jTextField2ditime.setEditable(false);

        jLabel7.setText("Search Diagnosis using Patient Id:");

        jTextField1searchdiagpid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1searchdiagpidKeyReleased(evt);
            }
        });

        jButton1previewemail.setText("Preview Email");
        jButton1previewemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1previewemailActionPerformed(evt);
            }
        });

        jButton1ddreset.setText("Reset");
        jButton1ddreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ddresetActionPerformed(evt);
            }
        });

        jButton1dlogout.setText("Logout");
        jButton1dlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1dlogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jTextField1didate, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2ditime, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(130, 130, 130)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jButton1savediagnosis)
                                .addGap(43, 43, 43)
                                .addComponent(jButton1previewemail)
                                .addGap(71, 71, 71)
                                .addComponent(jButton2openasses)
                                .addGap(41, 41, 41)
                                .addComponent(jButton1ddreset, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jButton1dlogout))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(301, 301, 301)
                                .addComponent(jLabel4))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField1dpid, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField1searchdiagpid, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(448, 448, 448)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(411, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField1didate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField2ditime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField1searchdiagpid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1dpid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2openasses)
                            .addComponent(jButton1savediagnosis)
                            .addComponent(jButton1previewemail)
                            .addComponent(jButton1ddreset)
                            .addComponent(jButton1dlogout)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1savediagnosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1savediagnosisActionPerformed
        // TODO add your handling code here:

        if (jTextField1dpid.getText().isEmpty() || jTextArea1dreport.getText().isEmpty() || jTextArea2medication.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "More than one field has been left  empty!!");

        } else if (jTextField1dpid.getText().length() > 5) {
            JOptionPane.showMessageDialog(null, "Patient id should not exceed 5 characters!!");

        } else {
            try {

                String sql3 = "INSERT INTO diagnosis( patientId, diagnosisreport, medication,Date,TIME) VALUES (?,?,?,?,?)";
                conn2 = DriverManager.getConnection("jdbc:mysql://localhost:3306/prs", "root", "");
                p3 = conn2.prepareStatement(sql3);
                p3.setString(1, jTextField1dpid.getText());
                p3.setString(2, jTextArea1dreport.getText());
                p3.setString(3, jTextArea2medication.getText());
                p3.setString(4, jTextField1didate.getText());
                p3.setString(5, jTextField2ditime.getText());
                p3.executeUpdate();
                JOptionPane.showMessageDialog(null, "Diagnosis saved successfully!");

            } catch (HeadlessException | SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
        TableDiag();
    }//GEN-LAST:event_jButton1savediagnosisActionPerformed

    public void TableDiag() {
        try {
            String sql3 = "SELECT diagnosisId, patientId, diagnosisreport, medication, Date, TIME FROM diagnosis ";
            conn2 = DriverManager.getConnection("jdbc:mysql://localhost:3306/prs", "root", "");
            p3 = conn2.prepareStatement(sql3);
            r3 = p3.executeQuery();
            jTable1diagnosis.setModel(DbUtils.resultSetToTableModel(r3));

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }
    private void jButton2openassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2openassesActionPerformed
        // TODO add your handling code here:

        Doctor d = new Doctor();
        d.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButton2openassesActionPerformed

    private void jTextField1searchdiagpidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1searchdiagpidKeyReleased
        // TODO add your handling code here:
        try {
            conn2 = DriverManager.getConnection("jdbc:mysql://localhost:3306/prs", "root", "");
            String sql3 = "SELECT * FROM diagnosis WHERE patientId=? ";
            p3 = conn2.prepareStatement(sql3);
            p3.setString(1, String.valueOf(jTextField1searchdiagpid.getText()));
            r3 = p3.executeQuery();
            jTable1diagnosis.setModel(DbUtils.resultSetToTableModel(r3));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);

        }
    }//GEN-LAST:event_jTextField1searchdiagpidKeyReleased

    private void jButton1previewemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1previewemailActionPerformed
        // TODO add your handling code here:
        if (jTextField1dpid.getText().isEmpty() || jTextArea1dreport.getText().isEmpty() || jTextArea2medication.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "More than one field has been left  empty!!");

        } else if (jTextField1dpid.getText().length() > 5) {
            JOptionPane.showMessageDialog(null, "Patient id should not exceed 5 characters!!");

        } else {
            Email2 e2 = new Email2();
            e2.setVisible(true);

        }
    }//GEN-LAST:event_jButton1previewemailActionPerformed

    private void jTextField1dpidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1dpidKeyPressed
        // TODO add your handling code here:
        char c7 = evt.getKeyChar();
        if (Character.isLetter(c7)) {
            //can't enter a textfield if entered character is not a number
            jTextField1dpid.setEditable(false);
            //error message
            JOptionPane.showMessageDialog(null, "Please enter a number only!!");

        } else {
            jTextField1dpid.setEditable(true);

        }
    }//GEN-LAST:event_jTextField1dpidKeyPressed

    private void jButton1ddresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ddresetActionPerformed
        // TODO add your handling code here:
        jTextField1dpid.setText("");
        jTextArea1dreport.setText("");
        jTextArea2medication.setText("");

    }//GEN-LAST:event_jButton1ddresetActionPerformed

    private void jTable1diagnosisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1diagnosisMouseClicked
        // TODO add your handling code here:
          DefaultTableModel model9 = (DefaultTableModel) jTable1diagnosis.getModel();
        int selectedRowIndex = jTable1diagnosis.getSelectedRow();

        jTextField1dpid.setText(model9.getValueAt(selectedRowIndex, 1).toString());
        jTextArea1dreport.setText(model9.getValueAt(selectedRowIndex, 2).toString());
        jTextArea2medication.setText(model9.getValueAt(selectedRowIndex, 3).toString());
      
           
       
    }//GEN-LAST:event_jTable1diagnosisMouseClicked

    private void jButton1dlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1dlogoutActionPerformed
        // TODO add your handling code here:
         int p3= JOptionPane.showConfirmDialog(null, "Are you sure you want to log out?","Log out",JOptionPane.YES_NO_OPTION);
        if(p3 == 0){
        this.dispose();
        Login l3 = new Login();
        l3.setVisible(true);
        }
    }//GEN-LAST:event_jButton1dlogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {

        } catch (InstantiationException ex) {
            ex.printStackTrace();
        } catch (IllegalAccessException ex) {
            ex.printStackTrace();
        } catch (UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Diagnosis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1ddreset;
    private javax.swing.JButton jButton1dlogout;
    private javax.swing.JButton jButton1previewemail;
    private javax.swing.JButton jButton1savediagnosis;
    private javax.swing.JButton jButton2openasses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1diagnosis;
    public static javax.swing.JTextArea jTextArea1dreport;
    public static javax.swing.JTextArea jTextArea2medication;
    private javax.swing.JTextField jTextField1didate;
    public static javax.swing.JTextField jTextField1dpid;
    private javax.swing.JTextField jTextField1searchdiagpid;
    private javax.swing.JTextField jTextField2ditime;
    // End of variables declaration//GEN-END:variables
}
