/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patientrecordsystem;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author benja
 */
public class Email1 extends javax.swing.JFrame {

    Connection cone = null;
    PreparedStatement pe = null;
    ResultSet re = null;

    /**
     * Creates new form Email1
     */
    public Email1() {
        initComponents();
        showtableEmail();
        jTextField1subject.setText("Medical Assessment Report");
        //composing email content
        String fname = Doctor.jTextField3docfirstname.getText();
        String lname = Doctor.jTextField1docLastname.getText();
        String pid = Doctor.jTextField4docpid.getText();
         String weight = Doctor.jTextField8weight.getText();
         String bp = Doctor.jTextField9bp.getText();
        String pulse = Doctor.jTextField6pulserate.getText();
        
        String age = Doctor.jTextField5docpage.getText();
        String Temp = Doctor.jTextField7temp.getText();
        String allergies = String.valueOf(Doctor.jComboBox1allergies.getSelectedItem());
        String comp = Doctor.jTextArea1complains.getText();
        String comphist = Doctor.jTextArea2complainsHistory.getText();

        jTextPane1email.setText("Doctor FirstName                : " + fname + "\n\n"
                +               "Doctor LastName                 : " + lname + "\n\n"
                +               "Patient Id                      : " + pid + "\n\n"
                +               "Patient weight(Kg)              : " + weight + "\n\n"
                +               "Patient Blood_pressure(MMHg)    : " + bp + "\n\n"
                +               "Patient Pulse /MIN              : " + pulse + "\n\n"
                +               "Patient Age                     : " + age + "\n\n"
                +               "Patient Temperature (Celsius)   : " + Temp + "\n\n"
                +               "Does Patient have any allergies : " + allergies + "\n\n"
                +               "Complains                       : " + comp + "\n\n\n\n\n"
                +               "Complains History               : " + comphist + "\n\n\n\n\n\n\n\n\n\n"
                +               "***  We wish you a quick recovery ***"
        );

    }

    public void showtableEmail() {
        try {
            cone = DriverManager.getConnection("jdbc:mysql://localhost:3306/prs", "root", "");
            String sqle = "SELECT patientId,  patientEmail FROM patientdetails";
            pe = cone.prepareStatement(sqle);
            re = pe.executeQuery();
            jTable1email.setModel(DbUtils.resultSetToTableModel(re));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1email = new javax.swing.JTable();
        jButton1sendmail = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1searchaddress = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField1emailpid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane1email = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jTextField1emailfrom = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField1subject = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTable1email.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jTable1email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1emailMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1email);

        jButton1sendmail.setText("Send Email");
        jButton1sendmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1sendmailActionPerformed(evt);
            }
        });

        jLabel1.setText("To search patient email address enter patient id:");

        jTextField1searchaddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1searchaddressKeyReleased(evt);
            }
        });

        jLabel2.setText("To:");

        jLabel3.setText("Message:");

        jTextPane1email.setEditable(false);
        jScrollPane4.setViewportView(jTextPane1email);

        jLabel4.setText("From:");

        jTextField1emailfrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1emailfromActionPerformed(evt);
            }
        });

        jLabel5.setText("Subject:");

        jTextField1subject.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 854, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jButton1sendmail))
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(113, 113, 113)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField1emailfrom, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1subject, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1emailpid, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 48, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(72, 72, 72)
                                .addComponent(jTextField1searchaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1searchaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1emailpid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField1emailfrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField1subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jButton1sendmail)))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowClosed

    private void jTextField1searchaddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1searchaddressKeyReleased
        // TODO add your handling code here:
        try {
            cone = DriverManager.getConnection("jdbc:mysql://localhost:3306/prs", "root", "");
            String sqle = "SELECT patientEmail FROM patientdetails where patientId=?";
            pe = cone.prepareStatement(sqle);
            pe.setString(1, String.valueOf(jTextField1searchaddress.getText()));
            re = pe.executeQuery();
            jTable1email.setModel(DbUtils.resultSetToTableModel(re));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jTextField1searchaddressKeyReleased

    private void jTable1emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1emailMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model1 = (DefaultTableModel) jTable1email.getModel();
        int selectedRowIndex = jTable1email.getSelectedColumn();
        jTextField1emailpid.setText(model1.getValueAt(selectedRowIndex, 1).toString());


    }//GEN-LAST:event_jTable1emailMouseClicked

    private void jButton1sendmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1sendmailActionPerformed
        // TODO add your handling code here:
         if (jTextField1emailpid.getText().isEmpty() || jTextField1emailfrom.getText().isEmpty() || jTextPane1email.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "More than one fields have been left empty!!");
       }
       else {
        String toemail = jTextField1emailpid.getText();
        String fromemail = jTextField1emailfrom.getText();
        String fromemailpassword = "ragnar@321";
        String subject = jTextField1subject.getText();

        Properties properties = new Properties();
        properties.put("mail.smtp.auth", "true");
        properties.put("mail.smtp.starttls.enable", "true");
        properties.put("mail.smtp.host", "smtp.gmail.com");
        properties.put("mail.smtp.port", "587");

        Session session = Session.getDefaultInstance(properties, new javax.mail.Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(fromemail, fromemailpassword);
            }

        });
        try{
            MimeMessage message = new MimeMessage(session);
            message.setFrom(new InternetAddress(fromemail));
            message.addRecipient(Message.RecipientType.TO, new InternetAddress(toemail));
            message.setSubject(subject);
            message.setText(jTextPane1email.getText());
            Transport.send(message);
            JOptionPane.showMessageDialog(null, "Email sent successfully!");
            
            
            
        }catch(HeadlessException | MessagingException ex){
            JOptionPane.showMessageDialog(null, ex);
            
            
        }
        
         }

    }//GEN-LAST:event_jButton1sendmailActionPerformed

    private void jTextField1emailfromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1emailfromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1emailfromActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {

        } catch (InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Email1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1sendmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1email;
    private javax.swing.JTextField jTextField1emailfrom;
    private javax.swing.JTextField jTextField1emailpid;
    private javax.swing.JTextField jTextField1searchaddress;
    private javax.swing.JTextField jTextField1subject;
    private javax.swing.JTextPane jTextPane1email;
    // End of variables declaration//GEN-END:variables
}
