/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patientrecordsystem;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author benja
 */
public class Email2 extends javax.swing.JFrame {

    Connection conn9 = null;
    PreparedStatement p9 = null;
    ResultSet r9 = null;

    /**
     * Creates new form Email2
     */
    public Email2() {
        initComponents();
        tblshow();
        jTextField1email2subject.setText("Medical Diagnosis Report");
        //composing email contents

        String dpid = Diagnosis.jTextField1dpid.getText();
        String dreport = Diagnosis.jTextArea1dreport.getText();
        String pmedication = Diagnosis.jTextArea2medication.getText();

        jTextPane1memail.setText("Patient Id                    : " +    dpid + "\n\n"
                +                "Diagnosis report              : " +    dreport + "\n\n\n\n"
                +                "Patient Medication report     : " +    pmedication + "\n\n\n\n"
                +                 " ***  We wish you a quick recovery ***"
        );

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1email2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1email2to = new javax.swing.JTextField();
        jTextField1email2from = new javax.swing.JTextField();
        jTextField1email2subject = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1memail = new javax.swing.JTextPane();
        jButton1emailsend = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField1search1d2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1email2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1email2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1email2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1email2);

        jLabel1.setText("To:");

        jLabel2.setText("From:");

        jLabel3.setText("Subject:");

        jLabel4.setText("Message:");

        jTextField1email2subject.setEditable(false);

        jTextPane1memail.setEditable(false);
        jScrollPane2.setViewportView(jTextPane1memail);

        jButton1emailsend.setText("Send Email");
        jButton1emailsend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1emailsendActionPerformed(evt);
            }
        });

        jLabel5.setText("To search patient email address enter patient id:");

        jTextField1search1d2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1search1d2KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(48, 48, 48)
                        .addComponent(jTextField1search1d2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jButton1emailsend))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1email2to, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField1email2from)
                                .addComponent(jTextField1email2subject, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)))))
                .addContainerGap(269, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField1search1d2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1email2to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1email2from, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1email2subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jButton1emailsend)))
                .addContainerGap(230, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1search1d2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1search1d2KeyReleased
        // TODO add your handling code here:
        try {
            conn9 = DriverManager.getConnection("jdbc:mysql://localhost:3306/prs", "root", "");
            String sql9;
            sql9 = "SELECT patientEmail FROM patientdetails where patientId=?";
            p9 = conn9.prepareStatement(sql9);
            p9.setString(1, String.valueOf(jTextField1search1d2.getText()));
            r9 = p9.executeQuery();
            jTable1email2.setModel(DbUtils.resultSetToTableModel(r9));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }


    }//GEN-LAST:event_jTextField1search1d2KeyReleased

    private void jButton1emailsendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1emailsendActionPerformed
        // TODO add your handling code here:
         if (jTextField1email2to.getText().isEmpty() || jTextField1email2from.getText().isEmpty() || jTextPane1memail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "More than one fields have been left empty!!");
        }
       else {
        String toemail1 = jTextField1email2to.getText();
        String fromemail1 = jTextField1email2from.getText();
        String fromemailpassword = "ragnar@321";
        String subject1 = jTextField1email2subject.getText();
        
         Properties properties = new Properties();
        properties.put("mail.smtp.auth", "true");
        properties.put("mail.smtp.starttls.enable", "true");
        properties.put("mail.smtp.host", "smtp.gmail.com");
        properties.put("mail.smtp.port", "587");
        
         Session session = Session.getDefaultInstance(properties, new javax.mail.Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(fromemail1, fromemailpassword);
            }

        });
         
         try{
            MimeMessage message = new MimeMessage(session);
            message.setFrom(new InternetAddress(fromemail1));
            message.addRecipient(Message.RecipientType.TO, new InternetAddress(toemail1));
            message.setSubject(subject1);
            message.setText(jTextPane1memail.getText());
            Transport.send(message);
            JOptionPane.showMessageDialog(null, "Email sent successfully!");
            
            
            
        }catch(HeadlessException | MessagingException ex){
            JOptionPane.showMessageDialog(null, ex);
            
            
        }
        


         }
        
        
        
    }//GEN-LAST:event_jButton1emailsendActionPerformed

    private void jTable1email2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1email2MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model2 = (DefaultTableModel) jTable1email2.getModel();
        int selectedRowIndex = jTable1email2.getSelectedColumn();
        jTextField1email2to.setText(model2.getValueAt(selectedRowIndex, 1).toString());
        
        
    }//GEN-LAST:event_jTable1email2MouseClicked

    public void tblshow() {
        try {
            conn9 = DriverManager.getConnection("jdbc:mysql://localhost:3306/prs", "root", "");
            String sql9;
            sql9 = "SELECT patientId,  patientEmail FROM patientdetails";
            p9 = conn9.prepareStatement(sql9);
            r9 = p9.executeQuery();
            jTable1email2.setModel(DbUtils.resultSetToTableModel(r9));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {

        }
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Email2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1emailsend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1email2;
    private javax.swing.JTextField jTextField1email2from;
    private javax.swing.JTextField jTextField1email2subject;
    private javax.swing.JTextField jTextField1email2to;
    private javax.swing.JTextField jTextField1search1d2;
    private javax.swing.JTextPane jTextPane1memail;
    // End of variables declaration//GEN-END:variables
}
