/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patientrecordsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author benja
 */
public class Pharmacist extends javax.swing.JFrame {

    Connection conph = null;
    PreparedStatement pph = null;
    ResultSet rph = null;

    /**
     * Creates new form Pharmacist
     */
    public Pharmacist() {
        initComponents();
        showtablePh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1pharmacistmd = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1pmedph = new javax.swing.JTextArea();
        jButton1logoutph = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1prmedid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("PHARMACIST DASHBOARD");

        jTable1pharmacistmd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1pharmacistmd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1pharmacistmdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1pharmacistmd);

        jTextArea1pmedph.setEditable(false);
        jTextArea1pmedph.setColumns(20);
        jTextArea1pmedph.setLineWrap(true);
        jTextArea1pmedph.setRows(5);
        jTextArea1pmedph.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextArea1pmedph);

        jButton1logoutph.setText("Logout");
        jButton1logoutph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1logoutphActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter Patient Id to search presribed medication:");

        jTextField1prmedid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1prmedidKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1prmedidKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(395, 395, 395)
                                .addComponent(jButton1logoutph))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(59, 59, 59)
                                .addComponent(jTextField1prmedid, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1prmedid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButton1logoutph)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1prmedidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1prmedidKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1prmedidKeyPressed

    private void jTextField1prmedidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1prmedidKeyReleased
        // TODO add your handling code here:
        try {
            conph = DriverManager.getConnection("jdbc:mysql://localhost:3306/prs", "root", "");
            String sqlph;
            sqlph = "SELECT diagnosisId, patientId,  medication, Date,  TIME_FORMAT(TIME,'%h:%i:%s %p')TIME FROM diagnosis where patientId=?";
            pph = conph.prepareStatement(sqlph);
            pph.setString(1, String.valueOf(jTextField1prmedid.getText()));
            rph = pph.executeQuery();
            jTable1pharmacistmd.setModel(DbUtils.resultSetToTableModel(rph));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);

        }
    }//GEN-LAST:event_jTextField1prmedidKeyReleased

    private void jTable1pharmacistmdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1pharmacistmdMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model2 = (DefaultTableModel)jTable1pharmacistmd.getModel();
        int selectedRowIndex = jTable1pharmacistmd.getSelectedRow();
        jTextArea1pmedph.setText(model2.getValueAt(selectedRowIndex, 2).toString());
        
        
    }//GEN-LAST:event_jTable1pharmacistmdMouseClicked

    private void jButton1logoutphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1logoutphActionPerformed
        // TODO add your handling code here:
         int p5 = JOptionPane.showConfirmDialog(null, "Are you sure you want to log out?","Log out",JOptionPane.YES_NO_OPTION);
        if(p5 == 0){
        this.dispose();
        Login l  =  new Login();
        
        l.setVisible(true);
        }
    }//GEN-LAST:event_jButton1logoutphActionPerformed

    /**
     * @param args the command line arguments
     */
    public void showtablePh() {
        try {
            conph = DriverManager.getConnection("jdbc:mysql://localhost:3306/prs", "root", "");
            String sqlph;
            sqlph = "SELECT diagnosisId, patientId,  medication, Date,  TIME_FORMAT(TIME,'%h:%i:%s %p')TIME FROM diagnosis ";
            pph = conph.prepareStatement(sqlph);
            rph = pph.executeQuery();
            jTable1pharmacistmd.setModel(DbUtils.resultSetToTableModel(rph));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);

        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {

        } catch (InstantiationException ex) {
            ex.printStackTrace();
        } catch (IllegalAccessException ex) {
            ex.printStackTrace();
        } catch (UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pharmacist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1logoutph;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1pharmacistmd;
    private javax.swing.JTextArea jTextArea1pmedph;
    private javax.swing.JTextField jTextField1prmedid;
    // End of variables declaration//GEN-END:variables
}
